services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DEEPSEEK_API_KEY=sk-5d832b2f7c0a4f1187c3c2c619c680f4
      - CHATAIAPI_API_KEY=sk-kSN2ux4WdAPmpzUJX69qx6L51mlelE069TXKaWxIzhTyOoqg

  frontend:
    build: ./frontend
    ports:
      - "6000:80"
    depends_on:
      - backend
